Add new Form with dynamic enum taken from a faked API
ARKlab/Ark.Starters.SPA pull request #7
Opened 2024-01-19 14:33 UTC by AndreaLandiArk

Add new Form with dynamic enum taken from a faked API

2024-01-30 14:46 UTC, sean-sligo approved these changes

2024-03-07 10:14 UTC, AndreaCuneo requested changes

2024-03-07 10:14 UTC, AndreaCuneo commented on src/features/formExample/videoGamesForm.tsx
> +  const [isOpen, setIsOpen] = useState(false);
prefer https://chakra-ui.com/docs/hooks/use-boolean

2024-03-07 10:14 UTC, AndreaCuneo commented on src/lib/apiTypes.ts
> +export type ArkQueryParameters = {
Query is overlygeneric term.

this is correct for PagedQuery only.

2024-03-07 11:46 UTC, AndreaCuneo approved these changes

2024-03-07 12:50 UTC, merged