Permission Manager
ARKlab/Ark.Starters.SPA pull request #71
Opened 2024-05-03 13:10 UTC by AndreaLandiArk

Added HasPermission implementation for both msal and auth0
Added Protected Component with Fallback.
Added Protected Route with Fallback.

2024-05-03 14:57 UTC, AndreaCuneo requested changes

2024-05-03 14:57 UTC, AndreaCuneo commented on src/lib/authentication/authenticationSlice.ts
> +export const userSelector = (state: RootState) => state.auth.data?.userInfo;
define selectors in Slice.

https://redux-toolkit.js.org/api/createSlice#selectors

2024-05-03 14:57 UTC, AndreaCuneo commented on src/lib/authentication/components/protectedComponent.tsx
> +  component,
use children instead of component

2024-05-03 14:57 UTC, AndreaCuneo commented on src/lib/authentication/components/protectedRoute.tsx
> +const ProtectedRoute = ({
I don't understand the purpose of this. 

This change the <Routes> of the application routes which is not the purpose.
Like for <AuthOnly>, some Routes may be wrapped into HasPermission and fallback should be <Unauthorized> by default.

This component react only on changes to the 'context' and not to the User profile and thus the Permissions so I'm not sure how it works.

2024-05-03 14:57 UTC, AndreaCuneo commented on src/lib/authentication/components/protectedRoute.tsx
> +  element: React.ReactElement;
use children

2024-05-03 14:57 UTC, AndreaCuneo commented on src/lib/authentication/components/protectedRoute.tsx
> +    navigate(fallbackPath);
if, if the context change, indipendently if the browser is on this route, we trigger a navigate. Also, side effects in FuncionalComponents shouldn't be in a useEffect() ?

2024-05-03 14:57 UTC, AndreaCuneo commented on vite.config.ts.timestamp-1714464248720-625d33c226982.mjs
delete this

2024-05-03 14:57 UTC, AndreaCuneo commented on src/lib/authHelpers.ts
move under lib/authentication

2024-05-03 14:57 UTC, AndreaCuneo commented on src/lib/authentication/components/protectedComponent.tsx
> +  const { context } = useAuthContext();
shouldn't use the userInfo from the Slice?

2024-05-03 14:57 UTC, AndreaCuneo commented on src/lib/authentication/components/protectedRoute.tsx
> +  const { context } = useAuthContext();
shouldn't use slice data?

2024-05-03 14:57 UTC, AndreaCuneo commented on src/lib/authentication/components/protectedRoute.tsx
> +  return hasAllPermissions ? <>{children}</> : <Navigate to="/Unauthorized" />;
prefer to render Unauthorized component without navigation to preserve the url

2024-05-03 15:46 UTC, AndreaCuneo approved these changes

2024-05-06 13:24 UTC, sean-sligo approved these changes

2024-05-06 13:25 UTC, merged